spring:
  application:
    name: "demo"
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:mariadb://localhost/test
    username: taltest
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  flyway:
    enabled: true
  jpa:
    hibernate:
      show-sql: true
